# -*- coding: utf-8 -*-

# logging
logging: ~/git/oscar-instrument-catalogue/logging

# source file
source: ~/git/oscar-instrument-catalogue/example-instrument-catalogue.csv

# target file
target: ~/git/oscar-instrument-catalogue/example-instrument-catalogue.xml

# jinja2 template
template: instrument-catalogue-template.xml

# header information
individualName: Jörg Klausen
organisationName: MeteoSwiss
electronicMailAddress: joerg.klausen@meteoswiss.ch

# API endpoints
upload: https://oscardepl.wmo.int/surface/rest/api/wmd/upload/
#upload: https://oscar.wmo.int/surface/rest/api/wmd/upload/

# security token
token: here-goes-the-security-token