# -*- coding: utf-8 -*-

# logging
logging: ~/Public/git/oscar-instrument-catalogue/logging/

# source file
source: ~/Public/git/oscar-instrument-catalogue/example-instrument-catalogue.csv

# target file
target: ~/Public/git/oscar-instrument-catalogue/

# jinja2 template
template: instrument-catalogue-template.xml

# header information
individualName: Jörg Klausen
organisationName: MeteoSwiss
electronicMailAddress: joerg.klausen@meteoswiss.ch

# API endpoints
upload: https://oscardevt.meteoswiss.ch/surface/rest/api/wmd/upload/
#upload: https://oscar.wmo.int/surface/rest/api/wmd/upload/

# security token
token: 7091380d-0014-4ebf-9f7d-0699dd4cf5e1

